name: autoquill_ai
description: "Audio transcription desktop app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  path_provider: ^2.1.1
  get_it: ^7.6.4
  record: ^5.0.4
  audioplayers: ^6.4.0
  http: ^1.3.0
  hotkey_manager: ^0.2.3
  bot_toast: ^4.0.1
  desktop_multi_window: ^0.2.1
  pasteboard: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
